# Generated by Django 2.0.6 on 2018-07-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('contactno', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('hr_name', models.CharField(max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('vacancy', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField(default=0)),
                ('jobtype', models.CharField(max_length=100)),
                ('required_skills', models.CharField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naukri.Company')),
            ],
            options={
                'ordering': ('designation',),
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('contactno', models.BigIntegerField(default=0)),
                ('skills', models.CharField(max_length=100)),
                ('jobs', models.ManyToManyField(to='naukri.Job')),
            ],
            options={
                'ordering': ('s_name',),
            },
        ),
    ]
