# Generated by Django 2.0.7 on 2018-07-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contactno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='naukri.Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='contactno',
            field=models.CharField(max_length=10),
        ),
    ]
